[build]
  command = "npm run build"
  publish = "public/"

[[redirects]]
  from = "/recruiting-blog search=:search"
  to = "/.netlify/functions/getBlogs?search=:search"
  force=true
  status = 200

[[headers]]
  for = "/_elderjs/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
