[build]
  command = "npm run build"
  publish = "public/"

[[redirects]]
  from = "/recruiting-blog/"
  to = "/.netlify/functions/getBlogs"
  status = 301
  force = true

[[headers]]
  for = "/_elderjs/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
