[build]
  command = "npm run build"
  publish = "public/"

[[redirects]]
  from = "/recruiting-blog"
  query = {search = ":search"} # apply this rule for /old-path?search=example
  to = "/.netlify/functions/getBlogs/?search=:search"
  force=true
  status = 200

[[plugins]]
package = "@netlify/plugin-sitemap"
  [plugins.inputs]
  exclude = [
    "/fr/*",
  ]

[[headers]]
  for = "/_elderjs/*"
  [headers.values]
    cache-control = '''
      public,
      max-age=31536000,
      immutable'''
